### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by pixiaoxiao** [hyperf/mqtt-server-incubator#6]
服务开启后,使用三方的mqtt工具,订阅主题,如"ubXg47dA" ,服务端的主题,无法转发给其他订阅的客户端
![1709978343318](https://github.com/hyperf/mqtt-server-incubator/assets/19233453/ae3bade1-0dce-477c-a129-47802c9e37d1)
订阅主题的代码
![1709978456642](https://github.com/hyperf/mqtt-server-incubator/assets/19233453/43e52cfd-9358-4636-bf5a-462e0cfd8a25)

**Comment by sy-records** [comment]
你自己实现server的话，需要自己实现分发的逻辑，收到客户端的publish，分发给对应订阅的fd。

**Comment by pixiaoxiao** [comment]
好的 明白了
