### ISSUE TITLE
hyperf3.1 Attribute class Hyperf\MqttServer\Annotation\MQTTConnect does not have a constructor, cannot pass arguments

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [hyperf/mqtt-server-incubator#7]
![image](https://github.com/user-attachments/assets/d246b960-08f2-48b8-aac9-88a874deb544)
Fatal error: Uncaught Error: Attribute class Hyperf\MqttServer\Annotation\MQTTConnect does not have a constructor, cannot pass arguments in /opt/project/vendor/hyperf/di/src/Annotation/AnnotationReader.php:126
Stack trace:
#0 /opt/project/vendor/hyperf/di/src/Annotation/AnnotationReader.php(126): ReflectionAttribute->newInstance()
#1 /opt/project/vendor/hyperf/di/src/Annotation/Scanner.php(46): Hyperf\Di\Annotation\AnnotationReader->getAttributes()
#2 /opt/project/vendor/hyperf/di/src/Annotation/Scanner.php(116): Hyperf\Di\Annotation\Scanner->collect()
#3 /opt/project/vendor/hyperf/di/src/ClassLoader.php(56): Hyperf\Di\Annotation\Scanner->scan()
#4 /opt/project/bin/hyperf.php(27): Hyperf\Di\ClassLoader::init()
#5 /opt/project/bin/hyperf.php(33): {closure}()
#6 {main}
  thrown in /opt/project/vendor/hyperf/di/src/Annotation/AnnotationReader.php on line 126

**Comment by YanCunJu** [comment]
遇到同样的问题，怎么解决的？
